index:
    path: /
    controller: App\Controller\DefaultController::index

user_register:
    path: /register
    controller: App\Controller\RegistrationController::registerAction
    methods: [POST]
