user_register:
    path: /register
    controller: App\Controller\RegistrationController::registerAction
    methods: [POST]
user_change_password:
    path: /api/changedata
    controller: App\Controller\ChangeUserDataController::changeUserDataAction
    methods: [PUT]
user_login:
    path: /login
    controller: App\Controller\LoginController::loginAction
    methods: [POST]
api_login_check:
    path: /login_check

all_products:
    path: /api/products
    controller: App\Controller\ProductController::getAllPagination
    methods: [GET]
one_product:
    path: /api/products/{id}
    controller: App\Controller\ProductController::getOne
    methods: [GET]
add_product:
    path: /api/products
    controller: App\Controller\ProductController::add
    methods: [POST]
update_product:
    path: /api/products/{id}
    controller: App\Controller\ProductController::update
    methods: [PUT]
delete_product:
    path: /api/products/{id}
    controller: App\Controller\ProductController::delete
    methods: [DELETE]

all_meals:
    path: /api/meals
    controller: App\Controller\MealController::getAllPagination
    methods: [GET]
one_meal:
    path: /api/meals/{id}
    controller: App\Controller\MealController::getOne
    methods: [GET]
add_meal:
    path: /api/meals
    controller: App\Controller\MealController::add
    methods: [POST]
update_meal:
    path: /api/meals/{id}
    controller: App\Controller\MealController::update
    methods: [PUT]
delete_meal:
    path: /api/meals/{id}
    controller: App\Controller\MealController::delete
    methods: [DELETE]

one_userdetails:
    path: /api/user/details
    controller: App\Controller\PersonDetailsController::getDetailsForUser
    methods: [GET]
add_userdetails:
    path: /api/user/details
    controller: App\Controller\PersonDetailsController::add
    methods: [POST]
update_userdetails:
    path: /api/user/details
    controller: App\Controller\PersonDetailsController::update
    methods: [PUT]
delete_userdetails:
    path: /api/user/details
    controller: App\Controller\PersonDetailsController::delete
    methods: [DELETE]

show_planner:
    path: /api/planner
    controller: App\Controller\PlannerController::getItemsForWeek
    methods: [GET]
add_item_to_planner:
    path: /api/planner
    controller: App\Controller\PlannerController::addItem
    methods: [POST]
change_position_item_planner:
    path: /api/planner/item/{id}
    controller: App\Controller\PlannerController::changePosition
    methods: [PATCH]
delete_item_planner:
    path: /api/planner/item/{id}
    controller: App\Controller\PlannerController::deleteItem
    methods: [DELETE]